/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Util.ImageProcess;
import Util.ImageTransparency;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import neuralNetwork.Hopfield;
import static neuralNetwork.Main.getInputDataFromPath;
import static neuralNetwork.Main.getInputDataFromBufferImage;
import neuralNetwork.Matrix;
import neuralNetwork.Pattern;

/**
 *
 * @author Diana Quintanilla Perez
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    ImageProcess process;
    BufferedImage imageForTest = null;
    Hopfield net;
    int WIDTH = 40;
    int HEIGTH = 40;

    public GUI() {
        initComponents();
        imagesForTrain.setModel(getListModelOFImages());
        process = new ImageProcess();

    }

    private DefaultListModel getListModelOFImages() {
        DefaultListModel listModel = new DefaultListModel();
        File folder = new File("src/images");
        File[] listOfFiles = folder.listFiles();

        for (int i = 0; i < listOfFiles.length; i++) {
            if (listOfFiles[i].isFile()) {
                listModel.addElement(listOfFiles[i].getName());
            } else if (listOfFiles[i].isDirectory()) {
            }
        }
        return listModel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        imagesForTrain = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        train = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        searchImageForTest = new javax.swing.JButton();
        testImageSelected = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        imageToRecognized = new javax.swing.JLabel();
        imageRecognized = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        message = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(imagesForTrain);

        jLabel1.setText("Seleccione figuras para el entrenamiento");

        train.setText("Entrenar");
        train.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainActionPerformed(evt);
            }
        });

        jLabel2.setText("Seleccione un archivo para reconocer");

        searchImageForTest.setText("Buscar");
        searchImageForTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchImageForTestActionPerformed(evt);
            }
        });

        testImageSelected.setText("Reconocer letra del alfabeto Braile");
        testImageSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testImageSelectedActionPerformed(evt);
            }
        });

        jLabel3.setText("La imagen se reconoce como:");

        message.setText("Mensaje:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(testImageSelected)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(56, 56, 56))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(imageToRecognized, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addContainerGap()))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(train)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(imageRecognized, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(searchImageForTest))
                                    .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchImageForTest))
                        .addGap(18, 18, 18)
                        .addComponent(message)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(imageToRecognized, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(testImageSelected)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel3))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(train)
                    .addComponent(imageRecognized, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("empty-statement")
    private void trainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainActionPerformed

        int[] selectedIx = imagesForTrain.getSelectedIndices();
        if (selectedIx.length > 0) {
            double inputs[][][] = new double[selectedIx.length][10][10];
            net = new Hopfield(selectedIx.length);
            for (int i = 0; i < selectedIx.length; i++) {
                Object imageName = imagesForTrain.getModel().getElementAt(selectedIx[i]);
                double[] data = getInputDataFromPath("src/images/" + imageName.toString());
                double in[][] = {data};
                net.addInput(in,imageName.toString());
            }
             JOptionPane.showMessageDialog(null, "Red entrenada");
           
        }else{
             JOptionPane.showMessageDialog(null, "No se seleccionaron imagenes para entrenar" );
           
        }

    }//GEN-LAST:event_trainActionPerformed

    private void searchImageForTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchImageForTestActionPerformed

        imageForTest = this.process.getImageFromChooser("src/images");
        imageForTest = new ImageTransparency().toTransparency(imageForTest);
        //imageToRecognized.setIcon(new ImageIcon(imageForTest));
        System.out.println("h " + imageForTest.getHeight() + "w " + imageForTest.getWidth());
        int ratio = imageForTest.getHeight() / imageForTest.getWidth();
        int width = 20;
        int height = 30;
        BufferedImage scaled = this.process.scale(imageForTest, imageToRecognized.getWidth(), imageToRecognized.getHeight());
        imageToRecognized.setIcon(new ImageIcon(scaled));
         

    }//GEN-LAST:event_searchImageForTestActionPerformed

    private void testImageSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testImageSelectedActionPerformed
        Pattern p = null;
        if (this.imageForTest != null) {
            System.out.println("Test : ");
            double[] data = getInputDataFromBufferImage(this.imageForTest);
            double test[][] = {data};
            Matrix testInput = new Matrix(test);
            testInput.setName("test");
            p = net.execute(testInput);
            imageRecognized.setText(p.identifier);
        } else {
            this.message.setText("No se han seleccionado imagenes para entrenar");
        }
    }//GEN-LAST:event_testImageSelectedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imageRecognized;
    private javax.swing.JLabel imageToRecognized;
    private javax.swing.JList imagesForTrain;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel message;
    private javax.swing.JButton searchImageForTest;
    private javax.swing.JButton testImageSelected;
    private javax.swing.JButton train;
    // End of variables declaration//GEN-END:variables
}
